### PR TITLE
Bump bounds of transformers

### PR DESCRIPTION
**Pull request by tvh**
It compiles with the newer version

### CODE REVIEW

**Comment by TomMD** [comment]
Thanks!

**Comment by qrilka** [comment]
@TomMD @RaphaelJ GHC8 is out for some months already - any chance to see new versions of `friday`/`friday-devil` on hackage?

**Comment by TomMD** [comment]
I'm not sure I have permissions on hackage.  I'll find time for the latest merge request then find out and get the permissions if needed.

**Comment by TomMD** [comment]
@qrilka  Not exactly.  I asked @RaphaelJ for commit access when I expected to be having more time and interest in the subject.  Time is always tight, but I'm pretty sure both time and interest are tighter for Raphael who I understand joined a start-up one year ago and haven't heard from since.

**Comment by qrilka** [comment]
@TomMD are there any news about new hackage release?

**Comment by TomMD** [comment]
@qrilka I just tried and do not have permissions on hackage.

@RaphaelJ seeing as you are continuing to be MIA (missing in startup still?), I'm going to request the hackage admins to add me to the maintainers list.

**Comment by TomMD** [comment]
@RaphaelJ Actually, in keeping with the spirit of the hackage steps for "taking over a package" (not that I want to be sole maintainer, https://wiki.haskell.org/Taking_over_a_package) I am hereby asking for you to grant me co-maintainership of the package on hackage.  If I do not hear from you by December 1 I'll send this request to the hackage admins.

Cheers!

**Comment by TomMD** [comment]
@qrilka  

I now have hackage maintainership.

I intend to do a test build tonight and push to hackage.  Feel free to ping me if I don't keep to that.

**Comment by TomMD** [comment]
@qrilka A new `friday` package is on hackage.  I've never been a fan of Friday-devil (i.e. I have reasons to avoid the C library as a dependency) so if you'd like to do a package take-over and maintain that one then that's my suggestion on keeping it working.

**Comment by qrilka** [comment]
Actually our use of `friday` is quite small and I'll check tomorrow if we could just switch to `JuicyPixels` :)
I.e. if there is an option I'd prefer to switch as our needs in these libs are quite minuscule at least at the moment. Sorry...

**Comment by qrilka** [comment]
BTW @TomMD have you seen any recent comparisons between `JuicyPixels` and C image libraries?

**Comment by TomMD** [comment]
@qrilka I have not seen any recent comparisons, but I'd bet the author of JuicyPixels is aware of  the latest one.

**Pull request merged**
